@startuml 図3-6_オブジェクト図
left to right direction
object "<u>社員: 高橋洋平</u>" as k2 {
情報処理技術者試験 申し出 = 2020年10月21日
LinuC試験Level1 申し出 = 2021年3月28日
}
object "<u>社員: 樋口正之</u>" as k1 {
情報処理技術者試験 申し出 = 2023/04/27
}
object "<u>資格 </u>" as car1 {
情報処理技術者試験の情報処理安全確保支援士
}
object "<u>資格</u>" as car2 {
LinuC試験Level1
}
k1 -- car1
k2 -- car2
k2 -- car1
@enduml