@startuml 貸出管理システムのクラス図
'left to right direction
class "商品" as empty_car {
商品名
形式 
}
class "注文" as car {
注文日
数量
}
class "重要顧客" as rental {
}
class "顧客" as customer {
氏名
住所
}
empty_car "1" -ri- "*" car
car "*" -ri- "1" customer
customer <|-down- rental

@enduml