@startuml 演習3-2_CL_医師と患者と医局と診療記録

class 医師 {
---
}
class 患者 {
---
}
class 病院 {
---
}
class 小児科 {
---
}
class 内科 {
---
}
class 外科 {
---
}
医師 <-- 患者
病院 "1" *-- 小児科
病院 "1" *-- 内科
病院 "1" *-- 外科
外科 "1" *-- 医師
内科 "1" *-- 医師
小児科 "1" *-- 医師


@enduml