@startuml 製品を製造するアクティビティ図
title 製品を製造する
|営業部門|
|営業部門|
|販売代理店|
|販売代理店|
|製造部門|
|製造部門|
|営業部門|
    start
    :発注;
|営業部門|
    |販売代理店|
        :在庫調査;
        :受注;
if () then (在庫あり)
:;
else (在庫なし)
|製造部門|
:製造;
endif
    |販売代理店|
:発送;
|営業部門|
:入金確認;
|販売代理店|
:検収/支払い;
stop
@enduml