@startuml ステートマシン図_診察予約システム

state 医院診察予約 {
予約と確認 -> あなたの順番 :名前と電話番号を記入し登録
予約と確認 -> あなたの順番 :名前か電話番号を入力してから取消
あなたの順番 -left-> メニュー
メニュー -down-> 予約と確認
予約と確認 -up-> メニュー
メニュー --> 今の順番 :現在診察中の患者の順番を表示
今の順番  --> メニュー :名前か電話番号を入力してから確認
    [*] -> メニュー
    メニュー -> [*]
}
@enduml