@startuml ユースケース図_診察予約システム
left to right direction
actor 利用者 #DDDDDD;line:black;line.bold;
actor 看護師 #DDDDDD;line:black;line.bold;
rectangle 医院診察予約{
usecase メニュー 
usecase 予約と確認1
usecase 予約と確認2
usecase 予約と確認3
usecase 今の順番 
usecase あなたの順番 

}
利用者 --> メニュー
メニュー --> 予約と確認1
メニュー --> 予約と確認2
メニュー --> 予約と確認3
メニュー --> 今の順番:<<現在診察中の患者の順番を表示>>
看護師 --> 今の順番:<<診察が終わると看護士が現在の患者番号を一つ増やす>>
予約と確認1 --> あなたの順番:<<名前と電話番号を記入し登録>>
予約と確認2 --> あなたの順番:<<名前か電話番号を入力してから確認>>
予約と確認3 --> メニュー:<<名前か電話番号を入力してから取消>>
@enduml